language: python
sudo: false
env:
- FAKEINV_DIR=/tmp/fakeinv
python:
- 3.6
- 3.5
- 3.4
- 3.3
- 3.2
- 2.7
- 2.6
- pypy3
- pypy
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- python setup.py bdist_wheel
- pip install dist/iso4217-*.whl flake8
script:
- if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" && "$TRAVIS_PYTHON_VERSION" != "3.2" ]]; then
    flake8 .;
  fi
- pushd /tmp && python -m iso4217.test && popd
after_success:
- export GIT_AUTHOR_NAME="$(git log --pretty=format:'%an' -n1)"
- export GIT_AUTHOR_EMAIL="$(git log --pretty=format:'%ae' -n1)"
- pip install sphinx-fakeinv
- rm -rf $FAKEINV_DIR
- git init $FAKEINV_DIR
- git -C $FAKEINV_DIR config user.name "$GIT_AUTHOR_NAME"
- git -C $FAKEINV_DIR config user.email "$GIT_AUTHOR_EMAIL"
- git -C $FAKEINV_DIR remote add origin git@github.com:$TRAVIS_REPO_SLUG.git
- git -C $FAKEINV_DIR checkout -b gh-pages
- sphinx-fakeinv iso4217 > $FAKEINV_DIR/objects.inv
- touch $FAKEINV_DIR/.nojekyll
- git -C $FAKEINV_DIR add objects.inv .nojekyll
- git -C $FAKEINV_DIR commit -m "Fake objects.inv  $TRAVIS_COMMIT"
- openssl aes-256-cbc -K $encrypted_5187b045a9f7_key -iv $encrypted_5187b045a9f7_iv -in deploy_rsa.enc -out deploy_rsa -d
- chmod 400 deploy_rsa
- if [[ "$TRAVIS_PYTHON_VERSION" = "3.5" ]]; then
    ssh-agent sh -c "ssh-add deploy_rsa && git -C $FAKEINV_DIR push -f origin gh-pages";
  else
    echo "$TRAVIS_PYTHON_VERSION";
  fi
